name: Build and deploy docker image on DockerHub

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the docker image 
      run: docker build -t $DOCKER_USER/$REPO_NAME:${{ github.sha }} .
    - name: Push the docker image
      run: docker push $DOCKER_USER/$REPO_NAME